game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
wait(13)
game:GetService("ReplicatedStorage").DefaultChatSystemChatEvents.SayMessageRequest:FireServer(unpack({[1] = "AUTO TOP Pegasus",[2] = "All"}))
